### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ast261** [Claymore1297/kernel_motorola_miami#1]
Sorry to write an issue here, but I have not found another way for a contact.

On the AICP website I can only find OTA weekly zips. They cannot be flashed with my TWRP.
Where can I find a full ROM to flash on miami ?

**Comment by Claymore1297** [comment]
Hi,

You can find a working tarp here:
https://github.com/Claymore1297/device_motorola_miami/releases/tag/1.0

Regards

**Comment by ast261** [comment]
Great work!
Thanks
